//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.20 at 05:17:49 PM CEST 
//


package it.cnr.cool.mail.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.cnr.cool.mail.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.cnr.cool.mail.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RiferimentiTelematici }
     * 
     */
    public RiferimentiTelematici createRiferimentiTelematici() {
        return new RiferimentiTelematici();
    }

    /**
     * Create an instance of {@link CodiceFiscale }
     * 
     */
    public CodiceFiscale createCodiceFiscale() {
        return new CodiceFiscale();
    }

    /**
     * Create an instance of {@link Segnatura }
     * 
     */
    public Segnatura createSegnatura() {
        return new Segnatura();
    }

    /**
     * Create an instance of {@link Livello }
     * 
     */
    public Livello createLivello() {
        return new Livello();
    }

    /**
     * Create an instance of {@link RiferimentoDocumentiCartacei }
     * 
     */
    public RiferimentoDocumentiCartacei createRiferimentoDocumentiCartacei() {
        return new RiferimentoDocumentiCartacei();
    }

    /**
     * Create an instance of {@link Destinatario }
     * 
     */
    public Destinatario createDestinatario() {
        return new Destinatario();
    }

    /**
     * Create an instance of {@link AggiornamentoConferma }
     * 
     */
    public AggiornamentoConferma createAggiornamentoConferma() {
        return new AggiornamentoConferma();
    }

    /**
     * Create an instance of {@link Riferimenti }
     * 
     */
    public Riferimenti createRiferimenti() {
        return new Riferimenti();
    }

    /**
     * Create an instance of {@link AnnullamentoProtocollazione }
     * 
     */
    public AnnullamentoProtocollazione createAnnullamentoProtocollazione() {
        return new AnnullamentoProtocollazione();
    }

    /**
     * Create an instance of {@link UnitaOrganizzativa }
     * 
     */
    public UnitaOrganizzativa createUnitaOrganizzativa() {
        return new UnitaOrganizzativa();
    }

    /**
     * Create an instance of {@link Mittente }
     * 
     */
    public Mittente createMittente() {
        return new Mittente();
    }

    /**
     * Create an instance of {@link Intestazione }
     * 
     */
    public Intestazione createIntestazione() {
        return new Intestazione();
    }

    /**
     * Create an instance of {@link Comune }
     * 
     */
    public Comune createComune() {
        return new Comune();
    }

    /**
     * Create an instance of {@link Ruolo }
     * 
     */
    public Ruolo createRuolo() {
        return new Ruolo();
    }

    /**
     * Create an instance of {@link Fascicolo }
     * 
     */
    public Fascicolo createFascicolo() {
        return new Fascicolo();
    }

    /**
     * Create an instance of {@link Classifica }
     * 
     */
    public Classifica createClassifica() {
        return new Classifica();
    }

    /**
     * Create an instance of {@link Risposta }
     * 
     */
    public Risposta createRisposta() {
        return new Risposta();
    }

    /**
     * Create an instance of {@link Telefono }
     * 
     */
    public Telefono createTelefono() {
        return new Telefono();
    }

    /**
     * Create an instance of {@link IndirizzoPostale }
     * 
     */
    public IndirizzoPostale createIndirizzoPostale() {
        return new IndirizzoPostale();
    }

    /**
     * Create an instance of {@link Messaggio }
     * 
     */
    public Messaggio createMessaggio() {
        return new Messaggio();
    }

    /**
     * Create an instance of {@link Destinazione }
     * 
     */
    public Destinazione createDestinazione() {
        return new Destinazione();
    }

    /**
     * Create an instance of {@link Nazione }
     * 
     */
    public Nazione createNazione() {
        return new Nazione();
    }

    /**
     * Create an instance of {@link Persona }
     * 
     */
    public Persona createPersona() {
        return new Persona();
    }

    /**
     * Create an instance of {@link AOO }
     * 
     */
    public AOO createAOO() {
        return new AOO();
    }

    /**
     * Create an instance of {@link Toponimo }
     * 
     */
    public Toponimo createToponimo() {
        return new Toponimo();
    }

    /**
     * Create an instance of {@link MessaggioRicevuto }
     * 
     */
    public MessaggioRicevuto createMessaggioRicevuto() {
        return new MessaggioRicevuto();
    }

    /**
     * Create an instance of {@link Fax }
     * 
     */
    public Fax createFax() {
        return new Fax();
    }

    /**
     * Create an instance of {@link PrimaRegistrazione }
     * 
     */
    public PrimaRegistrazione createPrimaRegistrazione() {
        return new PrimaRegistrazione();
    }

    /**
     * Create an instance of {@link Impronta }
     * 
     */
    public Impronta createImpronta() {
        return new Impronta();
    }

    /**
     * Create an instance of {@link ContestoProcedurale }
     * 
     */
    public ContestoProcedurale createContestoProcedurale() {
        return new ContestoProcedurale();
    }

    /**
     * Create an instance of {@link Amministrazione }
     * 
     */
    public Amministrazione createAmministrazione() {
        return new Amministrazione();
    }

    /**
     * Create an instance of {@link Descrizione }
     * 
     */
    public Descrizione createDescrizione() {
        return new Descrizione();
    }

    /**
     * Create an instance of {@link OraRegistrazione }
     * 
     */
    public OraRegistrazione createOraRegistrazione() {
        return new OraRegistrazione();
    }

    /**
     * Create an instance of {@link Nome }
     * 
     */
    public Nome createNome() {
        return new Nome();
    }

    /**
     * Create an instance of {@link IndirizzoTelematico }
     * 
     */
    public IndirizzoTelematico createIndirizzoTelematico() {
        return new IndirizzoTelematico();
    }

    /**
     * Create an instance of {@link PerConoscenza }
     * 
     */
    public PerConoscenza createPerConoscenza() {
        return new PerConoscenza();
    }

    /**
     * Create an instance of {@link ConfermaRicezione }
     * 
     */
    public ConfermaRicezione createConfermaRicezione() {
        return new ConfermaRicezione();
    }

    /**
     * Create an instance of {@link Procedimento }
     * 
     */
    public Procedimento createProcedimento() {
        return new Procedimento();
    }

    /**
     * Create an instance of {@link Identificatore }
     * 
     */
    public Identificatore createIdentificatore() {
        return new Identificatore();
    }

    /**
     * Create an instance of {@link TestoDelMessaggio }
     * 
     */
    public TestoDelMessaggio createTestoDelMessaggio() {
        return new TestoDelMessaggio();
    }

    /**
     * Create an instance of {@link Provincia }
     * 
     */
    public Provincia createProvincia() {
        return new Provincia();
    }

    /**
     * Create an instance of {@link NotificaEccezione }
     * 
     */
    public NotificaEccezione createNotificaEccezione() {
        return new NotificaEccezione();
    }

    /**
     * Create an instance of {@link Denominazione }
     * 
     */
    public Denominazione createDenominazione() {
        return new Denominazione();
    }

    /**
     * Create an instance of {@link Responsabile }
     * 
     */
    public Responsabile createResponsabile() {
        return new Responsabile();
    }

    /**
     * Create an instance of {@link Cognome }
     * 
     */
    public Cognome createCognome() {
        return new Cognome();
    }

    /**
     * Create an instance of {@link CAP }
     * 
     */
    public CAP createCAP() {
        return new CAP();
    }

    /**
     * Create an instance of {@link Titolo }
     * 
     */
    public Titolo createTitolo() {
        return new Titolo();
    }

    /**
     * Create an instance of {@link Civico }
     * 
     */
    public Civico createCivico() {
        return new Civico();
    }

    /**
     * Create an instance of {@link Origine }
     * 
     */
    public Origine createOrigine() {
        return new Origine();
    }

    /**
     * Create an instance of {@link Allegati }
     * 
     */
    public Allegati createAllegati() {
        return new Allegati();
    }

    /**
     * Create an instance of {@link DescrizioneMessaggio }
     * 
     */
    public DescrizioneMessaggio createDescrizioneMessaggio() {
        return new DescrizioneMessaggio();
    }

    /**
     * Create an instance of {@link Documento }
     * 
     */
    public Documento createDocumento() {
        return new Documento();
    }

}
